---
apiVersion: v1
kind: Service
metadata:
  name: probes-app-svc
  namespace: probes-demo
  labels:
    user: emre
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: probes-app